require: rubocop-rspec

# disable some cops that suggest changes which are incompatible with old Rubies
Performance/RegexpMatch:
  Enabled: false
Performance/UnfreezeString:
  Enabled: false
Style/Encoding:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/UnpackFirst:
  Enabled: false
