AllCops:
  Exclude:
    - '**/vendor/**/*' # vendored dependencies
    - './tmp/**/*'
  NewCops: enable
  RubyInterpreters:
    - ruby
    - rake
  TargetRubyVersion: 2.4 # really 2.1, but 2.4 is lowest supported by rubocop

# ignore weird looking regexps in specs, we wanna keep those
Lint/DuplicateRegexpCharacterClassElement:
  Exclude: ['spec/**/*']
Lint/LiteralInInterpolation:
  Exclude: ['spec/**/*']
Lint/MixedRegexpCaptureTypes:
  Exclude: ['spec/**/*']
