name: gouteur

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Node                        # for client_side_validations js test
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Prepare
        run: bundle install --jobs 4
      - name: Test
        run: bundle exec gouteur
